sudo: required
services:
  - docker
before_install:
  # name of the tag doesn't matter, but we'll use it later
  # tag it, where is the filename? what is the context?
  - docker build -t bensonryan/react-test -f client/Dockerfile.dev ./client
  # if we want to test other services, do more builds, then add to the scripts list

script:
  # use the same tag as before
  # by default, react tests watch, need to use -- --coverage to run and exit
  - docker run -e CI=true bensonryan/react-test npm test -- --coverage

# push our builds to dockerhub, all 3 of them (using prod dockerfiles)
after_success:
  - docker build -t bensonryan/docker-calculator-client ./client
  - docker build -t bensonryan/docker-calculator-nginx ./nginx
  - docker build -t bensonryan/docker-calculator-server ./server
  - docker build -t bensonryan/docker-calculator-worker ./worker